# Label-Selector system
# labels can be arbitrary

apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
  - name: client
    image: dropzone/multi-containers-client
    ports:
      - containerPort: 3000
