apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web # defines how the deployment object identifies the pods
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
      - name: client
        image: dropzone/multi-containers-client
        ports:
        - containerPort: 3000
