sudo: required
services:
  - docker

before_install:
  - docker build -t dropzone/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run dropzone/react-test npm test -- --coverage

after_success:
  - docker build -t dropzone/multi-containers-client ./client
  - docker build -t dropzone/multi-containers-nginx ./nginx
  - docker build -t dropzone/multi-containers-server ./server
  - docker build -t dropzone/multi-containers-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push dropzone/multi-containers-client
  - docker push dropzone/multi-containers-nginx
  - docker push dropzone/multi-containers-server
  - docker push dropzone/multi-containers-worker
